import { Header } from "@/app/_components/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="container mx-auto min-h-dvh grid grid-rows-[auto_1fr_auto]">
      <Header />
      <main className="px-4">{children}</main>
      <footer>
        <div className="container mx-auto py-8">
          <p className="text-center text-sm text-gray-500">
            &copy; {new Date().getFullYear()} MyPortfolio. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
